import "@/app/globals.css";
import Link from "next/link";
import Logout from "@/components/logoutBtn";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";

export const metadata = {
  title: "Admin Page",
  description: "Generated by Next.js",
};

export default async function RootLayout({ children }) {
  try {
    const cookieStore = await cookies();
    const token = cookieStore.get("token");

    if (!token) {
      redirect("/admin-login");
    }
  } catch (error) {
    console.error("Cookie access error:", error);
    redirect("/admin-login");
  }

  return (
    <>
      <div className="md:grid grid-cols-12 h-screen">
        <header className="md:col-span-2 ">
          {/* Desktop navbar */}
          <div className="hidden md:flex h-full w-full p-2 bg-gray-600 text-white flex-col justify-between">
            <nav>
              <ul className="flex flex-col gap-4">
                <Link href="/admin/dashboard">
                  <li className="hover:border border-gray-300 rounded-md p-4">
                    Dashboard
                  </li>
                </Link>
                <Link href="/admin/add_car">
                  <li className="hover:border border-gray-300 rounded-md p-4">
                    Add Car
                  </li>
                </Link>
                <Link href="/admin/all_cars">
                  <li className="hover:border border-gray-300 rounded-md p-4">
                    All Cars
                  </li>
                </Link>
              </ul>
            </nav>
            <div>
              <Logout />
            </div>
          </div>
          {/* mobile navbar */}
          <div className="md:hidden bottom-4 left-1/2 -translate-x-1/2 fixed bg-black text-white z-20  rounded-2xl">
            <nav>
              <ul className="flex justify-center items-center text-nowrap gap-4">
                <Link href="/admin/dashboard">
                  <li className=" border-gray-300 rounded-md p-4">Dashboard</li>
                </Link>
                <Link href="/admin/add_car">
                  <li className=" border-gray-300 rounded-md p-4">Add Car</li>
                </Link>
                <Link href="/admin/all_cars">
                  <li className=" border-gray-300 rounded-md p-4">All Cars</li>
                </Link>
              </ul>
            </nav>
          </div>
        </header>
        <div className="md:col-span-10 col-span-12 bg-gray-100 overflow-y-scroll">
          {children}
        </div>
      </div>
    </>
  );
}
