import "@/app/globals.css";
import Link from "next/link";

export const metadata = {
  title: "Admin Page",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="grid grid-cols-12 h-screen">
        <header className="md:col-span-2">
          <div className="hidden md:flex h-full w-full p-2 bg-gray-600 text-white flex-col justify-between">
            <nav>
              <ul className="flex flex-col gap-4">
                <Link href="/admin/dashboard">
                  <li className="hover:border border-gray-300 rounded-md p-4">
                    Dashboard
                  </li>
                </Link>
                <Link href="/admin/add_car">
                  <li className="hover:border border-gray-300 rounded-md p-4">
                    Add Car
                  </li>
                </Link>
                <Link href="/admin/all_cars">
                  <li className="hover:border border-gray-300 rounded-md p-4">
                    All Cars
                  </li>
                </Link>
              </ul>
            </nav>
            <div>
              <button className="bg-red-500 w-full py-2 px-4 rounded-md text-white cursor-pointer hover:bg-red-600 transition-colors">
                Log Out
              </button>
            </div>
          </div>
        </header>
        <div className="md:col-span-10 col-span-12">{children}</div>
      </body>
    </html>
  );
}
